# Generated by Django 5.1.1 on 2026-09-23 17:02

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('listing_type', models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale'), ('shortlet', 'Shortlet')], max_length=20)),
                ('bedrooms', models.PositiveSmallIntegerField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('agent_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['listing_type', 'bedrooms'], name='listings_li_listing_28d950_idx'), models.Index(fields=['price'], name='listings_li_price_d6caaa_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='listing_price_must_be_positive')],
            },
        ),
    ]
